/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'mario' at '7/13/15 9:25 AM' with Gradle 2.5
 *
 * @author mario, @date 7/13/15 9:25 AM
 */


import net.kaleidos.gradle.plugins.EmergerPlugin
import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        EmergerPlugin lib = new EmergerPlugin()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
